# ----------------------------------------
# Application
# ----------------------------------------
spring.application.name=joomoney-api
spring.profiles.active=local

server.forward-headers-strategy=framework

#-----------------------------------------
# Messages
#-----------------------------------------
spring.messages.basename=messages/messages

# ----------------------------------------
# Hikari Connection Pool
# ----------------------------------------
spring.datasource.hikari.pool-name=JoomoneyHikariPool
spring.datasource.hikari.connection-test-query=SELECT 1

# ----------------------------------------
# JPA / Hibernate
# ----------------------------------------
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ----------------------------------------
# JWT / Token Configuration
# ----------------------------------------
jwt.token-prefix=Bearer
jwt.header=Authorization

# ----------------------------------------
# Mail (Gmail SMTP)
# ----------------------------------------
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.display-name=Joomoney
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
