package jooyung.com.joomoney_api.auth.dto

data class DeviceInformationDto (
    val deviceId: String,
    val deviceType: String, // PC, MOBILE, TABLET, ...
    val os: String, // WINDOWS, MACOS, LINUX, ANDROID, IOS, IPADOS, ...
    val platform: String, // WEB, APP, ...
)